### ISSUE TITLE
How to update to newest version

### ISSUE THREAD

**Issue by tormodboga** [neffs/hassio-addons#1]
How can I update the addon to the newest version? I installed this previously (mid february) and it has deconz version 2.04.99, but now you upgraded to a newer version of deconz and also added the QT GUI option. How can I update to this newest version?

Do I have to uninstall, and install again? If so, will I lose any settings/changes etc? Will the devices still be there and recognised as before?

**Comment by neffs** [comment]
you should be able to update using the web interface, just like with other hassio add on.

 uninstalling works too. to be sure you can create a backup using the deconz web ui (phoscon)
